openapi: 3.1.0
info:
  title: Live Sensor Data for Viam Robots
  description: Get real-time air quality and presence detection data from live sensors.
  version: "1.0.0"
servers:
  - url: https://viam-mcp.onrender.com
paths:
  /get_readings:
    get:
      operationId: getReadings
      summary: Get air quality readings
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful air quality data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  readings:
                    type: object
                  status:
                    type: object
        "401":
          description: Unauthorized

  /history:
    get:
      operationId: getHistory
      summary: Get historical air quality readings (last 24 hours)
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Historical air quality data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                        data:
                          type: object
        "401":
          description: Unauthorized

  /presence:
    get:
      operationId: getPresence
      summary: Get real-time presence detection readings
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Presence detection data response
          content:
            application/json:
              schema:
                type: object
                properties:
                  readings:
                    type: object
                  presence_state:
                    type: string
                    example: "Static Target"
        "401":
          description: Unauthorized
